<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Codex额度悬浮窗</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="CodexQuotaIsland.App.xaml" />
    <ApplicationDefinition Include="CodexQuotaIsland.App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="assets\*.png" />
    <Resource Include="assets\*.png" />
  </ItemGroup>
</Project>
